name: Deploy To-Do App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code von GitHub auschecken
      uses: actions/checkout@v3

    - name: Per SSH auf AWS einloggen und App aktualisieren
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.64.217.19
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ec2-user/to-do-liste
          git pull origin main
          docker rm -f mein-todo-container || true
          docker build --no-cache -t todo-devops-app .
          docker run -d -p 80:8000 --name mein-todo-container todo-devops-app